Repository Salary-Dev/Salary_BE, pull requests merged in 2024-11, with the labels that each got.

#14 [Init] GitHub actions
  .github/workflows/deploy.yml
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/salary_BE/salary/Controller/TrendQuizController.java
  src/main/java/salary_BE/salary/Service/TrendQuizService.java
Labels: ⚙ Setting, 🌏 Deploy

#20 [feat] mock 데이터 기본 레포지터리 및 서비스 구현
  src/main/java/salary_BE/salary/Domain/Word.java
  src/main/java/salary_BE/salary/Repository/UserRepository.java
  src/main/java/salary_BE/salary/Repository/WordLikeRepository.java
  src/main/java/salary_BE/salary/Repository/WordRepository.java
  src/main/java/salary_BE/salary/Service/UserService.java
  src/main/java/salary_BE/salary/Service/WordLikeService.java
  src/main/java/salary_BE/salary/Service/WordService.java
Labels: ✨ Feature

#25 feat: 트렌드 퀴즈 학습 여부 반영
  src/main/java/salary_BE/salary/Controller/TrendQuizController.java
  src/main/java/salary_BE/salary/Repository/AttendanceRepository.java
  src/main/java/salary_BE/salary/Repository/TodayStudyRepository.java
  src/main/java/salary_BE/salary/Service/AttendanceService.java
  src/main/java/salary_BE/salary/Service/TodayStudyService.java
  src/main/java/salary_BE/salary/Service/TrendQuizService.java
Labels: ✨ Feature

#30 [Feat] 단어 학습 기능 구현
  src/main/java/salary_BE/salary/Controller/WordLikeController.java
  src/main/java/salary_BE/salary/Domain/Attendance.java
  src/main/java/salary_BE/salary/Repository/WordLikeRepository.java
  src/main/java/salary_BE/salary/Service/TrendQuizService.java
  src/main/java/salary_BE/salary/Service/WordLikeService.java
Labels: ✨ Feature

#32 [Feat] 날짜별 학습률 조회 기능 구현
  src/main/java/salary_BE/salary/Controller/AttendanceController.java
  src/main/java/salary_BE/salary/Service/AttendanceService.java
Labels: ✨ Feature

#36 [Feat] 오늘 학습 단어 조회 구현
  src/main/java/salary_BE/salary/Controller/AttendanceController.java
  src/main/java/salary_BE/salary/Repository/AttendanceRepository.java
  src/main/java/salary_BE/salary/Service/AttendanceService.java
Labels: ✨ Feature

#37 [Feat] 오늘 학습 과목 조회 구현
  src/main/java/salary_BE/salary/Controller/TodayStudyController.java
  src/main/java/salary_BE/salary/Service/TodayStudyService.java
Labels: ✨ Feature

#40 [Feat] 부분 단어 검색 기능 구현
  src/main/java/salary_BE/salary/Controller/WordController.java
  src/main/java/salary_BE/salary/Repository/WordRepository.java
  src/main/java/salary_BE/salary/Service/WordService.java
Labels: ✨ Feature

#42 [Refactor] 유저 다중 데이터 처리
  src/main/java/salary_BE/salary/Repository/AttendanceRepository.java
  src/main/java/salary_BE/salary/Service/AttendanceService.java
Labels: 🔨 Refactor

#44 refactor: mock 유저 데이터 적용
  src/main/java/salary_BE/salary/Controller/WordLikeController.java
  src/main/java/salary_BE/salary/DTO/WordLikeDto.java
  src/main/java/salary_BE/salary/Repository/WordLikeRepository.java
  src/main/java/salary_BE/salary/Service/WordLikeService.java
Labels: 🔨 Refactor

#49 [Feat] 단어장 저장 여부 반환 추가
  src/main/java/salary_BE/salary/DTO/WordmainDto.java
  src/main/java/salary_BE/salary/Repository/WordLikeRepository.java
  src/main/java/salary_BE/salary/Service/WordService.java
Labels: ✨ Feature

#50 [Refactor] 오늘 학습 단어 조회 수정
  src/main/java/salary_BE/salary/Service/AttendanceService.java
Labels: 🔨 Refactor

#54 [Refactor] 트렌드 퀴즈 프롬포트 조건 추가
  src/main/java/salary_BE/salary/Service/TrendQuizService.java
Labels: 🔨 Refactor

#55 [Refactor] 트렌드 퀴즈 프롬포트 반영
  src/main/java/salary_BE/salary/Service/TrendQuizService.java
Labels: 🔨 Refactor

#59 [Feat] 학습률 자동 스케줄링 구현
  src/main/java/salary_BE/salary/Scheduler/AttendanceScheduler.java
  src/main/java/salary_BE/salary/Service/TrendQuizService.java
  src/main/java/salary_BE/salary/Service/UserService.java
Labels: ✨ Feature, 🔨 Refactor

#57 [Feat] aws s3 연동 환경 구축
  build.gradle
  src/main/java/salary_BE/salary/Controller/FileUploadController.java
  src/main/java/salary_BE/salary/Util/S3Config.java
Labels: ⚙ Setting, ✨ Feature

#60 [Feat] 오늘 학습 단어 추가 로직 자동화
  src/main/java/salary_BE/salary/Repository/AttendanceRepository.java
  src/main/java/salary_BE/salary/Scheduler/AttendanceScheduler.java
Labels: ✨ Feature, 🔨 Refactor

#64 [Feat] 시드 적립/사용 (변경) 및 조회 기능 구현
  src/main/java/salary_BE/salary/Controller/SeedController.java
  src/main/java/salary_BE/salary/Domain/Attendance.java
  src/main/java/salary_BE/salary/Domain/User.java
  src/main/java/salary_BE/salary/Repository/AttendanceRepository.java
  src/main/java/salary_BE/salary/Repository/UserRepository.java
  src/main/java/salary_BE/salary/Service/AttendanceService.java
  src/main/java/salary_BE/salary/Service/SeedService.java
Labels: ✨ Feature

#68 [Feat] 오늘 학습 단어 자동화 도입
  src/main/java/salary_BE/salary/Scheduler/AttendanceScheduler.java
Labels: ✨ Feature

#70 [Feat] 아티클 기능 구현 및 학습 여부 반영
  src/main/java/salary_BE/salary/Controller/ArticleController.java
  src/main/java/salary_BE/salary/Controller/WordLikeController.java
  src/main/java/salary_BE/salary/DTO/ArticleDto.java
  src/main/java/salary_BE/salary/Domain/Article.java
  src/main/java/salary_BE/salary/Domain/Shorts.java
  src/main/java/salary_BE/salary/Domain/WordLike.java
  src/main/java/salary_BE/salary/Repository/ArticleRepository.java
  src/main/java/salary_BE/salary/Service/ArticleService.java
  src/main/java/salary_BE/salary/Service/WordService.java
Labels: ✨ Feature

#73 [Feat] - refresh token도입 + logout
  src/main/java/salary_BE/salary/Config/SecurityConfig.java
  src/main/java/salary_BE/salary/Controller/ReissueController.java
  src/main/java/salary_BE/salary/Controller/UserController.java
  src/main/java/salary_BE/salary/Domain/Refresh.java
  src/main/java/salary_BE/salary/JWT/CustomLogoutFilter.java
  src/main/java/salary_BE/salary/JWT/JWTFilter.java
  src/main/java/salary_BE/salary/JWT/JWTUtil.java
  src/main/java/salary_BE/salary/JWT/LoginFilter.java
  src/main/java/salary_BE/salary/Repository/RefreshRepository.java
Labels: ✨ Feature

#77 [Refactor] 시드 사용 예외 처리
  src/main/java/salary_BE/salary/Service/SeedService.java
Labels: 🐞 BugFix, 🔨 Refactor

#80 [Feat] 유저 생성 시 학습률 테이블 생성
  src/main/java/salary_BE/salary/Domain/User.java
  src/main/java/salary_BE/salary/Event/UserCreatedEvent.java
  src/main/java/salary_BE/salary/Listener/UserCreatedEventListener.java
  src/main/java/salary_BE/salary/Listener/UserEntityListener.java
  src/main/java/salary_BE/salary/Repository/UserRepository.java
  src/main/java/salary_BE/salary/Scheduler/AttendanceScheduler.java
  src/main/java/salary_BE/salary/Service/UserService.java
  src/test/java/salary_BE/salary/Integration/UserServiceIntegrationTest.java
  src/test/java/salary_BE/salary/Listener/UserEntityListenerTest.java
  src/test/java/salary_BE/salary/Scheduler/AttendanceSchedulerTest.java
  src/test/java/salary_BE/salary/Service/UserServiceTest.java
Labels: ✨ Feature
